### ISSUE TITLE
"Array" displayed for file name and description of first file uploaded

### ISSUE THREAD

**Issue by jackaponte** [backdrop-contrib/html5_upload#5] opened 2017-04-11 03:53 UTC
With the HTML5 Upload module enabled, if I use a core File field to upload one or more files, the first file in the batch is uploaded with the filename set to and displayed as `Array`. If multiple files are being uploaded in the batch, the other filenames and descriptions load properly. This wasn't always happening; seems to have started with a relatively recent core upgrade.

I know that's rather sparse on details; let me know if I can help fill in any blanks!

**Comment by laryn** [comment] 2017-05-11 22:42
Confirmed for me, too:
<img width="215" alt="screen shot 2017-05-11 at 4 50 11 pm" src="https://cloud.githubusercontent.com/assets/871421/25974940/25b176cc-3671-11e7-82d2-6d260ead3819.png">

**Comment by jackaponte** [comment] 2017-05-24 23:34
Just checked and this problem persists with the Backdrop 1.7.0 upgrade applied.

A few additional notes:

- Upon uploading one or more files to a file field, but before saving the node, I see the following error: `Notice: Array to string conversion in backdrop_write_record() (line 7978 of /var/www/backdrop/core/includes/common.inc).`
- When I tried debugging this about a month ago I determined that in `html5_upload.module` this value is being set incorrectly for the first file uploaded in a given set: `$_FILES['files']['name'][$new_name] = $original_files['name'][$upload_name][$i];`. It seems like it's something with how `$delta` or `$index` or `$new_name` are being set, but I spent quite a while on it and couldn't sort it out. :(

**Comment by olafgrabienski** [comment] 2017-06-21 15:52
Same here with Backdrop 1.7.0. Unfortunately I can't help with the code but will be happy to test a PR. @biolithic Are you still maintaining HTML5 upload?

**Comment by olafgrabienski** [comment] 2017-06-28 13:50
@laryn @jackaponte Last week I ran also in the `Array` issue with *HTML5 Upload*. There are now some editors preparing the site, so the issue becomes quite urgent for me. Do you have any idea how to fix the issue?

I can however give some more input now, as I found related messages in *DBlog*. Maybe they help to get an idea what is happening:

> PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'public://PATH-TO/MY-FILE.pdf' for key 'uri': INSERT INTO {file_managed} (fid, uid, filename, uri, filemime, filesize, status, timestamp) VALUES (default, :db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6); Array ( [:db_insert_placeholder_0] => 22 [:db_insert_placeholder_1] => Array [:db_insert_placeholder_2] => public://seiten/info-blatt_stand_06_2017.pdf [:db_insert_placeholder_3] => application/pdf [:db_insert_placeholder_4] => 1667833 [:db_insert_placeholder_5] => 0 [:db_insert_placeholder_6] => 1498652747 ) in backdrop_write_record() (line 8017 of /PATH-TO/core/includes/common.inc).

> EntityStorageException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'public://PATH-TO/MY-FILE.PDF' for key 'uri' in EntityDatabaseStorageController->save() (Zeile 552 von /PATH-TO/core/modules/entity/entity.controller.inc).

**Comment by laryn** [comment] 2017-06-28 15:00
@olafgrabienski @jackaponte @biolithic - I'll admit I'm not 100% sure what the code that treated the first file differently was for, so this PR was just an experiment in removing the code that referenced the `$first` variable. Do some testing and feel free to comment/critique...

**Comment by jackaponte** [comment] 2017-06-28 18:50
> Last week I ran also in the Array issue with HTML5 Upload. There are now some editors preparing the site, so the issue becomes quite urgent for me. Do you have any idea how to fix the issue?

@olafgrabienski Sadly no, I never managed to fix it and wound up disabling it on the site I recently launched.

> I can however give some more input now, as I found related messages in DBlog. Maybe they help to get an idea what is happening:

Hmm; I don't think I ever observed those sorts of issues on my site, but if I notice them when testing HTML5 Upload again in the future I'll let you know!

And thanks for the patch, @laryn; I don't think I'll be able to check it very soon but I'll try to at some point.

**Comment by olafgrabienski** [comment] 2017-06-28 20:32
@laryn Thanks for the PR! I just tested it on my dev site, and everything seems to be fine. I was able to upload several images via an image field and a couple of PDF files via a file field. I also played a bit around with the files (removed one, added another one). There was no `Array` filename but only correct ones, and I found none of the above mentioned messages in the *DBlog*.

Regarding the different treatment of the first file, I have no idea. @laryn The relevant code is also in the ported Drupal sandbox module (https://www.drupal.org/sandbox/z7/1348240), maybe ask the maintainer?

**Comment by olafgrabienski** [comment] 2017-09-29 20:46
In https://github.com/backdrop-contrib/html5_upload/issues/5#issuecomment-311665877 I mentioned some messages in the DBlog which I thought were related to this issue. I've just tested *HTML5 Upload* again on a Backdrop 1.8.0 site with a couple of images, and I didn't see these messages, so not sure if they were really related.

That said, the *Array* filename issue is still the case in Backdrop 1.8.0. There is @laryn's [suggestion](https://github.com/backdrop-contrib/html5_upload/commit/ed352f0de61d6acdd323f1302d48e07cb2707e35) which seems to work even if we're not sure if the first file should be treated otherwise. I guess we could need more feedback. @jackaponte Have you been able to check it in the meantime? @biolithic What do you think about it?

**Comment by ghost** [comment] 2018-07-02 07:42
Linked PR works for me (fixes the issue of first uploaded image being named 'Array').

**Comment by jackaponte** [comment] 2019-02-09 23:13
> That said, the _Array_ filename issue is still the case in Backdrop 1.8.0. There is @laryn's [suggestion](https://github.com/backdrop-contrib/html5_upload/commit/ed352f0de61d6acdd323f1302d48e07cb2707e35) which seems to work even if we're not sure if the first file should be treated otherwise. I guess we could need more feedback. @jackaponte Have you been able to check it in the meantime?

Sorry to take so very long to respond, @olafgrabienski! @laryn's PR #6 works well for me, fixing the problem with the naming of the first filename of the upload; everything else seems to be working fine still with the fix in place. I'll let you know if I notice anything amiss with continued use, but I'd say that PR is ready to merge!

**Comment by laryn** [comment] 2019-02-11 18:11
Thanks for the followup. I moved to the next step of maintainer transfer so will merge that PR when it is approved.
https://github.com/backdrop-ops/contrib/issues/321

**Comment by klonos** [comment] 2019-02-25 18:51
Things have happened 😄

**Comment by laryn** [comment] 2019-02-25 20:13
Merged. Will make a new release.

**Closed as completed by laryn** 2019-02-25 20:13 UTC
